### PR TITLE
add aero

### PR DESCRIPTION
**Pull request by teaforthecat**
that #or reader is pretty sweet for development in a micro service situation

### CODE REVIEW

**Comment by woodhull** [comment]
I did some work for Democracy Works years ago yet I still get alerts for issues on some of the projects. Is there some way to tell GH I would like to opt out completely that you know of? Some way to more completely exorcise me from your GH org?

**Comment by woodhull** [comment]
Nevermind, I figured out how to unwatch en mass. Sorry for the noise!

**Comment by teaforthecat** [comment]
reviewers: Sorry for all the updates. I think this PR looks good now. What do you think about removing `#resource-config/edn`. I initially left it in to ease upgrading, but I don't think it will be a hard lift to replace that with `#edn` when we do upgrade.

**Comment by mrichards42** [comment]
@teaforthecat I can't speak for other projects that use resource-config, but I know turbovote is planning on getting rid of it in favor of aero when we have the time (hopefully this year).

It isn't clear to me what the advantage of adding aero to resource-config is compared to just dropping resource-config and replacing it with aero.

**Comment by teaforthecat** [comment]
I thought this would make the transition easier.

**Comment by teaforthecat** [comment]
I'm guessing no one would care if I merged this and started the transition, so I'll do that later today.

**Comment by mrichards42** [comment]
@teaforthecat before you go ahead with this, can you talk about what the transition plan is? I guess I'd prefer that we go ahead with moving to aero all at once (i.e. replace resource-config) instead of piecemeal (i.e. change resource-config but still use it), but I don't have super strong feelings about it.

Since this is a core library used by a lot of our projects, could you have a couple folks from other projects have a look at this? (e.g. @dzcode @sduckett @troy)

**Comment by tank157** [comment]
We only seem to be using it in one project over on VIP that I can find right now, and it's locked at version "0.2.1". So long as you release a new version (maybe a major version since it'll now be backwards incompatible) then it wouldn't affect us. Eventually we'll be using `duct` in a new project to replace some bits of this, but we may need to keep the old codebase alive for some time.

**Comment by teaforthecat** [comment]
This is backwards compatible, fwiw, there isn't anything anyone would need to do to upgrade, it only makes the aero readers available for use. A major version bump would be ok still though.

**Comment by tank157** [comment]
Is it? I thought it removed the tag literal for `#resource-config/env`, which we make extensive use of, so I thought that would break. Does `aero` somehow take it over?

**Comment by teaforthecat** [comment]
oops, you're right. Sorry about that. It is breaking.

**Comment by mrichards42** [comment]
If we want to remove the data readers IMO the transition to using the new resource-config is the same lift as just replacing it with aero.

I buy your argument that adding aero to resource-config will make the transition off resource-config easier, since it would let us start using aero's data readers. So 👍 from me, but only if we reinstate the old resource-config data readers.

**Comment by gws** [comment]
I'm sort of -0 on this change - if you did release a new major version with any backward-incompatible changes that'd be OK, but it might also give the impression that this library is maintained, which I don't want :joy:

In projects where we've moved away from `resource-config` it's usually a find/replace to switch the env vars and changing `(config [...])` to something like `(get-in config [...])` or using something more idiomatic to the project. With this we'd still need to do a find/replace step on any project that chose to use it as a "bridge," but then come along later and do the same thing moving away from it entirely.

All that said, if this is _concretely helpful_ to any of our projects right now where we can't easily make the switch to aero, maybe that example could guide us?

**Comment by teaforthecat** [comment]
I guess I went back and forth on the backward compatibility, so I'll change that. And I do think there is just slight enough of an advantage to this way to start the transition, so I'd still like to go ahead. I could also make a note about this library being deprecated in the README. This should be totally transparent now, and only an option for people, not forcing anything.

**Comment by sduckett** [comment]
As an additional option for folks, if it keeps the readers, I'm OK with this. However, I feel like if I were in a project using `resource-config` and wanted `aero`, I'd probably set aside some time and commit to making the jump. (YMMV.)

**Pull request merged**
